if: tag IS blank
language: rust
sudo: false
rust:
  - stable
cache:
  cargo: true
env:
  global:
    - BIN_NAME=seeker
    - OPENSSL_STATIC=yes
    - DNS=8.8.8.8
matrix:
  include:
    - name: macOS Build
      os: osx
    - name: Linux Build
      os: linux

install:
  - rustup component add rustfmt clippy
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y upx; else brew install upx; fi
script:
  - mkdir -p artifacts
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo test --all
  - cargo build --release
  - strip target/release/$BIN_NAME
  - upx --ultra-brute target/release/$BIN_NAME
  - target/release/$BIN_NAME -V
  - cp target/release/$BIN_NAME artifacts/$BIN_NAME-$TRAVIS_OS_NAME
before_deploy:
  - export TRAVIS_TAG="preview"
  - export NOW=$(date +"%Y-%m-%d %H:%M:%S")
deploy:
  provider: releases
  api_key: $TOKEN
  skip_cleanup: true
  draft: true
  overwrite: true
  file_glob: true
  file: artifacts/$BIN_NAME-*
  name: $TRAVIS_COMMIT@$NOW
  on:
    branch: master
