[build]
pre-build = "ci/ubuntu-install-packages"

[build.env]
passthrough = ["RUST_BACKTRACE", "RUST_LOG", "DNS"]

[target.x86_64-unknown-linux-gnu]
runner = "qemu-system"

[target.x86_64-apple-darwin]
runner = "qemu-system"
