[target.x86_64-unknown-linux-gnu]
runner = 'sudo -E'

[target.x86_64-unknown-linux-musl]
runner = 'sudo -E'

[target.x86_64-apple-darwin]
runner = 'sudo -E'

[target.aarch64-apple-darwin]
runner = 'sudo -E'
